name: soliid_storage
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter  
  csv: ^6.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  mockito: ^5.4.4
  faker: ^2.1.0
